### ISSUE TITLE
converting to deeplearnjs 5

### ISSUE THREAD

**Issue by seranus** [chaosmail/deeplearnjs-caffe#11]
So there is a big issue, currently deeplearnjs doen't allow multiple instances https://github.com/PAIR-code/deeplearnjs/issues/562

I can't include a 5.0+ version and have to work with 4.0+ version since it already included here. There are significant changes with the 5 version.

**Comment by chaosmail** [comment]
Hi @seranus 

yeah that's true, the API changed quite a bit in the last few releases of deeplearnjs. However, I think updating this repo to the latest version of deeplearnjs is not that difficult, mainly fixing imports and changing APIs like `math.add(y, b)` to `y.add(b)`. Let me know if you want to help me out with this change!

Best, Christoph

**Comment by seranus** [comment]
since i wasn't using deeplearn before my biggest issue is that I can't find the old api documentation
