### ISSUE TITLE
unpkg link doesn't work

### ISSUE THREAD

**Issue by seranus** [chaosmail/deeplearnjs-caffe#8]
script link doesn't work

`Cannot find package "deeplearn-caffe"`

**Comment by chaosmail** [comment]
Hi @seranus 

thanks for the feedback. You are absolutely write, I never pushed the package to npm and hence the package is not available on unpkg neither. The reason for this was that the folks from deeplearnjs were thinking about moving to a dedicated npm namespace.

However, I will push it now to NPM as is and make it available.

Best,
Christoph

**Comment by chaosmail** [comment]
it's available now

* https://www.npmjs.com/package/deeplearn-caffe
* https://unpkg.com/deeplearn-caffe
